import { StyleSheet } from 'react-native';

export const onboardingStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F8FBF3',
  },
  slide: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 24,
    overflow: 'hidden',
  },
  slideGreen: {
    backgroundColor: '#F8FCF5',
  },
  slidePurple: {
    backgroundColor: '#F9F7FF',
  },
  slideOrange: {
    backgroundColor: '#FFF2E6',
  },
  skipBtn: {
    alignSelf: 'flex-end',
    padding: 4,
  },
  skipText: {
    fontSize: 12,
    fontFamily: 'Inter_18pt-SemiBold',
  },
  skipOrange: {
    color: '#FF5F00',
  },
  copyBlock: {
    marginTop: 24,
    zIndex: 2,
  },
  onboardingTitle: {
    fontSize: 27,
    lineHeight: 31,
    color: '#09111F',
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  titleAccent: {
    marginTop: -1,
  },
  orangeTitle: {
    color: '#FF6908',
  },
  onboardingSubtitle: {
    width: '86%',
    marginTop: 10,
    fontSize: 12,
    lineHeight: 18,
    color: '#111827',
    fontFamily: 'Inter_18pt-Regular',
  },
  decal: {
    position: 'absolute',
    opacity: 0.5,
    zIndex: 0,
  },
  walletHeroWrap: {
    marginTop: 26,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 360,
    zIndex: 2,
  },
  cashbackFloat: {
    position: 'absolute',
    bottom: 8,
    alignSelf: 'center',
    width: 168,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 10,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    shadowColor: '#0D3B17',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 18,
    elevation: 8,
  },
  earnedText: {
    color: '#101827',
    fontSize: 12,
    fontFamily: 'Inter_18pt-Medium',
  },
  earnedAmount: {
    marginTop: 2,
    color: '#147A2E',
    fontSize: 30,
    lineHeight: 34,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  cashbackPill: {
    marginTop: 5,
    borderRadius: 14,
    backgroundColor: '#DDF3CF',
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  cashbackPillText: {
    color: '#22733A',
    fontSize: 11,
    fontFamily: 'Inter_18pt-Bold',
  },
  giftHeroWrap: {
    marginTop: 20,
    alignItems: 'center',
    minHeight: 142,
    zIndex: 2,
  },
  giftGrid: {
    marginTop: -4,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 12,
    zIndex: 3,
  },
  giftCard: {
    width: '48%',
    height: 115,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    shadowColor: '#5C4B91',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.11,
    shadowRadius: 14,
    elevation: 5,
  },
  giftCardTop: {
    height: 60,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  giftAmazon: {
    backgroundColor: '#000000',
  },
  giftFlipkart: {
    backgroundColor: '#c5e4ffff',
  },
  giftMyntra: {
    backgroundColor: '#FF4E6A',
  },
  amazonGiftLogo: {
    color: '#FFFFFF',
    fontSize: 43,
    lineHeight: 45,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  amazonSmile: {
    position: 'absolute',
    bottom: 8,
    color: '#F7A90D',
    fontSize: 30,
    transform: [{ scaleX: 1.8 }],
  },
  flipkartGiftLogo: {
    color: '#FFFFFF',
    fontSize: 17,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  myntraGiftLogo: {
    color: '#FFFFFF',
    fontSize: 38,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  zomatoGiftLogo: {
    color: '#EF2634',
    fontSize: 22,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  giftCardBottom: {
    flex: 1,
    paddingHorizontal: 11,
    paddingVertical: 9,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  giftName: {
    color: '#171B24',
    fontSize: 14,
    fontFamily: 'Inter_18pt-Bold',
  },
  giftOffer: {
    alignItems: 'flex-end',
  },
  upToText: {
    color: '#5F43E7',
    fontSize: 8,
    fontFamily: 'Inter_18pt-Bold',
  },
  percentText: {
    color: '#5037D8',
    fontSize: 12,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  brandGhostAmazon: {
    position: 'absolute',
    top: 40,
    left: 26,
    color: '#A06E35',
    opacity: 0.45,
    fontSize: 31,
    fontFamily: 'Inter_18pt-ExtraBold',
    transform: [{ rotate: '-8deg' }],
  },
  brandGhostFlipkart: {
    position: 'absolute',
    top: 25,
    alignSelf: 'center',
    color: '#F6C54B',
    opacity: 0.8,
    fontSize: 42,
    fontFamily: 'Inter_18pt-ExtraBold',
    transform: [{ rotate: '-12deg' }],
  },
  brandGhostMyntra: {
    position: 'absolute',
    top: 52,
    right: 48,
    color: '#F28D8F',
    opacity: 0.58,
    fontSize: 42,
    fontFamily: 'Inter_18pt-ExtraBold',
    transform: [{ rotate: '12deg' }],
  },
  topStoresPanel: {
    marginTop: 24,
    borderRadius: 16,
    padding: 13,
    backgroundColor: '#FFFFFF',
  },
  panelHeader: {
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  panelTitle: {
    color: '#1B1D22',
    fontSize: 13,
    fontFamily: 'Inter_18pt-Bold',
  },
  gridGlyph: {
    color: '#8A95A3',
    fontSize: 18,
    fontFamily: 'Inter_18pt-Bold',
  },
  storeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 9,
  },
  storeCell: {
    width: '31%',
    aspectRatio: 1.1,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 4,
  },
  morePlus: {
    fontSize: 28,
    color: '#334155',
    fontFamily: 'Inter_18pt-Medium',
  },
  moreText: {
    fontSize: 10,
    color: '#475569',
    fontFamily: 'Inter_18pt-SemiBold',
    marginTop: 2,
  },
  securePanel: {
    marginTop: 17,
    minHeight: 73,
    borderRadius: 14,
    backgroundColor: '#FFE6D0',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 3,
  },
  shieldCircle: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#FFF4E8',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 11,
  },
  secureCopy: {
    flex: 1,
  },
  secureTitle: {
    color: '#1B2329',
    fontSize: 13,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  secureText: {
    marginTop: 2,
    color: '#646B73',
    fontSize: 10,
    lineHeight: 13,
    fontFamily: 'Inter_18pt-Medium',
  },
  startedButton: {
    marginTop: 32,
    minHeight: 48,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 11,
    zIndex: 4,
  },
  startedText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  startedArrow: {
    color: '#FFFFFF',
    fontSize: 24,
    marginTop: -2,
    fontFamily: 'Inter_18pt-SemiBold',
  },
  pagination: {
    position: 'absolute',
    bottom: 47,
    left: 0,
    right: 0,
    height: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 11,
    zIndex: 6,
  },
  dot: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: '#D7E2D3',
  },
  dotActive: {
    backgroundColor: '#0E7A2E',
  },
  dotPurple: {
    backgroundColor: '#6147E8',
  },
  dotOrange: {
    backgroundColor: '#FF6A00',
  },
  nextFab: {
    position: 'absolute',
    bottom: 30,
    right: 28,
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: '#16A34A',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    zIndex: 10,
  },
  nextFabPurple: {
    backgroundColor: '#6147E8',
  },
  nextFabOrange: {
    backgroundColor: '#FF6A00',
  },
});

export const loginStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F8FBF3' },
  screen: {
    flex: 1,
    backgroundColor: '#F8FBF3',
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 28,
  },
  absCash: {
    position: 'absolute',
    zIndex: 1,
  },
  absDecor: {
    position: 'absolute',
    opacity: 0.55,
    zIndex: 0,
  },
  brandWrap: {
    alignItems: 'center',
    marginTop: 30,
  },
  brandMain: {
    fontSize: 28,
    fontFamily: 'Inter_18pt-ExtraBold',
    color: '#111410',
    zIndex: 2,
  },
  brandAccent: {
    color: '#5F983A',
  },
  brandSub: {
    marginTop: 4,
    fontSize: 13,
    fontFamily: 'Inter_18pt-Medium',
    color: '#61695D',
    letterSpacing: 1.4,
  },
  heroPad: {
    height: 70,
  },
  featuresCard: {
    marginTop: 10,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DFE9D5',
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-around',
    elevation: 2,
    shadowColor: '#5E8F3A',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  featureCol: {
    width: '32%',
    alignItems: 'center',
    position: 'relative',
  },
  featureIconCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#EEF5E7',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  featureTitle: {
    fontSize: 12,
    fontFamily: 'Inter_18pt-Bold',
    color: '#182017',
  },
  featureSub: {
    marginTop: 1,
    fontSize: 10,
    fontFamily: 'Inter_18pt-Regular',
    color: '#5A6355',
    textAlign: 'center',
  },
  featureDivider: {
    position: 'absolute',
    right: -6,
    top: 6,
    width: 1,
    height: 42,
    backgroundColor: '#E2EBDD',
  },
  welcomeTitle: {
    marginTop: 20,
    fontSize: 34,
    fontFamily: 'Inter_18pt-Bold',
    color: '#172015',
  },
  welcomeSub: {
    marginTop: 4,
    marginBottom: 14,
    fontSize: 13,
    fontFamily: 'Inter_18pt-Regular',
    color: '#6B7467',
  },
  phoneInput: {
    minHeight: 52,
    borderRadius: 14,
    borderWidth: 1.4,
    borderColor: '#AFC49A',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  countryCode: {
    fontSize: 14,
    fontFamily: 'Inter_18pt-SemiBold',
    color: '#469739',
  },
  dropdown: {
    marginLeft: 6,
    marginRight: 10,
    fontSize: 16,
    color: '#6F7A68',
  },
  verticalDivider: {
    height: 24,
    width: 1,
    backgroundColor: '#CBD8BE',
    marginRight: 12,
  },
  phoneTextInput: {
    flex: 1,
    fontSize: 14,
    color: '#232A1F',
    fontFamily: 'Inter_18pt-Regular',
    paddingVertical: 8,
  },
  continueBtn: {
    minHeight: 48,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  continueText: {
    color: '#101610',
    fontSize: 19,
    fontFamily: 'Inter_18pt-SemiBold',
  },
  continueArrow: {
    color: '#101610',
    fontSize: 20,
    marginTop: -2,
    fontFamily: 'Inter_18pt-SemiBold',
  },
  cashbackCard: {
    marginTop: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#DFE9D5',
    backgroundColor: '#DFE9D5',
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
    flexDirection: 'row',
  },
  cashbackTextWrap: {
    flex: 1,
    marginLeft: 8,
  },
  cashbackTop: {
    fontSize: 14,
    color: '#4C5844',
    fontFamily: 'Inter_18pt-Regular',
  },
  cashbackMid: {
    marginTop: 1,
    fontSize: 16,
    lineHeight: 31,
    color: '#4B9139',
    fontFamily: 'Inter_18pt-Bold',
  },
  cashbackBottom: {
    marginTop: 2,
    fontSize: 14,
    color: '#7F8A77',
    fontFamily: 'Inter_18pt-Regular',
  },
  trustedRow: {
    marginTop: 14,
    marginBottom: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  trustedText: {
    color: '#5E6858',
    fontSize: 13,
    fontFamily: 'Inter_18pt-Regular',
  },
  trustedBold: {
    color: '#2D7E2A',
    fontFamily: 'Inter_18pt-Bold',
  },
});

export const otpStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F8FBF3' },
  screen: {
    flex: 1,
    backgroundColor: '#F8FBF3',
  },
  content: {
    paddingHorizontal: 18,
    paddingBottom: 28,
  },
  absCash: {
    position: 'absolute',
    zIndex: 0,
  },
  absDecor: {
    position: 'absolute',
    opacity: 0.45,
    zIndex: 0,
  },
  backArrow: {
    marginTop: 8,
    fontSize: 30,
    color: '#101410',
    width: 28,
    fontFamily: 'Inter_18pt-Regular',
  },
  brandWrap: {
    alignItems: 'center',
    marginTop: 12,
  },
  brandMain: {
    fontSize: 62,
    color: '#111410',
    letterSpacing: -1.3,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  brandAccent: {
    color: '#5F983A',
  },
  brandSub: {
    marginTop: 2,
    fontSize: 12,
    letterSpacing: 1.3,
    color: '#465141',
    fontFamily: 'Inter_18pt-Medium',
  },
  lockWrap: {
    marginTop: 28,
    marginBottom: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 50,
    color: '#1B3528',
    textAlign: 'center',
    fontFamily: 'Inter_18pt-Bold',
  },
  subtitle: {
    marginTop: 4,
    fontSize: 12,
    color: '#667067',
    textAlign: 'center',
    fontFamily: 'Inter_18pt-Regular',
  },
  phoneRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  phoneNumber: {
    fontSize: 19,
    color: '#182018',
    textAlign: 'center',
    fontFamily: 'Inter_18pt-Bold',
  },
  editIcon: {
    color: '#5A9B39',
    fontSize: 14,
  },
  otpPrompt: {
    marginTop: 20,
    marginBottom: 8,
    fontSize: 14,
    textAlign: 'center',
    color: '#454E45',
    fontFamily: 'Inter_18pt-Medium',
  },
  otpRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    paddingHorizontal: 6,
  },
  otpBox: {
    width: 53,
    height: 61,
    borderRadius: 10,
    borderWidth: 1.4,
    borderColor: '#91B576',
    backgroundColor: '#F8FBF3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  otpBoxActive: {
    borderColor: '#6A9F46',
    backgroundColor: '#FBFEF9',
  },
  cursorLine: {
    width: 2.5,
    height: 26,
    borderRadius: 2,
    backgroundColor: '#5E9A3E',
  },
  expireText: {
    textAlign: 'center',
    color: '#586257',
    fontSize: 15,
    fontFamily: 'Inter_18pt-Regular',
  },
  timerText: {
    color: '#63A33F',
    fontFamily: 'Inter_18pt-Bold',
  },
  resendText: {
    marginTop: 8,
    textAlign: 'center',
    color: '#596358',
    fontSize: 14,
    fontFamily: 'Inter_18pt-Regular',
  },
  resendLink: {
    color: '#5E9E3C',
    fontFamily: 'Inter_18pt-Bold',
  },
  securityCard: {
    marginTop: 18,
    borderRadius: 12,
    backgroundColor: '#EEF4E8',
    borderWidth: 1,
    borderColor: '#E3EED8',
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  securityIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    backgroundColor: '#E8F1DE',
  },
  securityTextWrap: {
    flex: 1,
  },
  securityTitle: {
    fontSize: 12,
    color: '#283229',
    fontFamily: 'Inter_18pt-SemiBold',
  },
  securitySub: {
    marginTop: 1,
    fontSize: 10,
    color: '#5A635B',
    fontFamily: 'Inter_18pt-Regular',
  },
  verifyBtn: {
    marginTop: 18,
    minHeight: 56,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  verifyText: {
    color: '#111610',
    fontSize: 17,
    fontFamily: 'Inter_18pt-SemiBold',
  },
  verifyArrow: {
    color: '#111610',
    fontSize: 23,
    marginTop: -2,
    fontFamily: 'Inter_18pt-SemiBold',
  },
  trustedRow: {
    marginTop: 14,
    marginBottom: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  laurel: {
    color: '#6EA14A',
    fontSize: 16,
    marginTop: -1,
  },
  trustedText: {
    color: '#4F5A4D',
    fontSize: 13,
    fontFamily: 'Inter_18pt-Regular',
  },
  trustedBold: {
    color: '#3E8A2E',
    fontFamily: 'Inter_18pt-Bold',
  },
});

export const homeStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F8FBF3' },
  container: { flex: 1, backgroundColor: '#F8FBF3' },
  scrollContent: { paddingHorizontal: 12, paddingTop: 8, paddingBottom: 16 },
  hero: {
    borderRadius: 18,
    backgroundColor: '#F2F8EC',
    borderWidth: 1,
    borderColor: '#E4EFDA',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  heroRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  heroLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  heroIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#16A34A',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  heroTitle: { fontSize: 20, color: '#1A2020', fontFamily: 'Inter_18pt-Bold' },
  heroSub: {
    fontSize: 11,
    color: '#374437',
    marginTop: 2,
    fontFamily: 'Inter_18pt-Regular',
  },
  heroWalletWrap: { alignItems: 'center', justifyContent: 'center' },
  coinsRow: {
    position: 'absolute',
    bottom: -4,
    left: -6,
    right: -6,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  coinBubble: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#F5C94C',
    alignItems: 'center',
    justifyContent: 'center',
  },
  offerList: { marginTop: 10 },
  offerCard: {
    width: 92,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E3EAE0',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 8,
    paddingVertical: 10,
    marginRight: 8,
  },
  offerLogoWrap: {
    height: 30,
    justifyContent: 'center',
  },
  offerBrand: {
    fontSize: 11,
    color: '#121212',
    fontFamily: 'Inter_18pt-SemiBold',
    minHeight: 34,
  },
  offerUpto: {
    fontSize: 10,
    color: '#586258',
    marginTop: 6,
    fontFamily: 'Inter_18pt-Regular',
  },
  offerPercent: {
    fontSize: 36,
    color: '#18803C',
    fontFamily: 'Inter_18pt-Bold',
  },
  offerCashback: {
    fontSize: 11,
    color: '#586258',
    fontFamily: 'Inter_18pt-Regular',
  },
  offerTag: {
    marginTop: 8,
    fontSize: 10,
    color: '#18803C',
    fontFamily: 'Inter_18pt-Bold',
  },
  ctaButton: {
    marginTop: 8,
    minHeight: 42,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  ctaText: {
    fontSize: 16,
    color: '#FFFFFF',
    fontFamily: 'Inter_18pt-SemiBold',
  },
  sectionCard: {
    marginTop: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2EADF',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  featureRow: { flexDirection: 'row' },
  featureItem: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRightWidth: 1,
    borderRightColor: '#E9EFE4',
  },
  featureItemLast: { borderRightWidth: 0 },
  featureHead: {
    fontSize: 14,
    color: '#2C8A37',
    fontFamily: 'Inter_18pt-Bold',
  },
  featureSub: {
    fontSize: 11,
    color: '#4E5A4E',
    marginTop: 2,
    fontFamily: 'Inter_18pt-Regular',
  },
  allStoreCard: {
    marginTop: 10,
    borderRadius: 14,
    backgroundColor: '#FFF2E7',
    borderWidth: 1,
    borderColor: '#F3DFCD',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  allStoreTitle: {
    fontSize: 19,
    color: '#C56911',
    fontFamily: 'Inter_18pt-Bold',
  },
  allStoreSub: {
    fontSize: 12,
    color: '#2D3632',
    marginTop: 3,
    fontFamily: 'Inter_18pt-Regular',
  },
  secondaryBtn: {
    marginTop: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#F1D0AF',
    paddingHorizontal: 13,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  secondaryBtnText: {
    fontSize: 14,
    color: '#B55C08',
    fontFamily: 'Inter_18pt-SemiBold',
  },
  giftCardWrap: {
    marginTop: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E6E4F6',
    backgroundColor: '#F5F4FD',
    padding: 10,
  },
  giftTitleRow: { flexDirection: 'row', alignItems: 'center' },
  giftTitle: {
    fontSize: 34,
    color: '#23233A',
    fontFamily: 'Inter_18pt-Bold',
    marginLeft: 8,
  },
  giftSub: {
    fontSize: 11,
    color: '#3D3D56',
    marginTop: 2,
    marginLeft: 38,
    fontFamily: 'Inter_18pt-Regular',
  },
  giftList: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  giftItem: {
    width: '19%',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E7E8EF',
    paddingBottom: 6,
    overflow: 'hidden',
  },
  giftLogoWrap: {
    height: 44,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#EFF1F4',
  },
  giftLogo: {
    height: 44,
    backgroundColor: '#111214',
    alignItems: 'center',
    justifyContent: 'center',
  },
  giftLogoBlue: { backgroundColor: '#0A54B4' },
  giftLogoPink: { backgroundColor: '#D63384' },
  giftLogoGreen: { backgroundColor: '#18803C' },
  giftLogoText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontFamily: 'Inter_18pt-Bold',
  },
  giftItemName: {
    fontSize: 9,
    color: '#1D2420',
    paddingHorizontal: 4,
    paddingTop: 5,
    fontFamily: 'Inter_18pt-SemiBold',
  },
  giftItemPct: {
    fontSize: 9,
    color: '#4A57C6',
    paddingHorizontal: 4,
    marginTop: 1,
    fontFamily: 'Inter_18pt-Bold',
  },
  purpleBtn: {
    marginTop: 10,
    minHeight: 34,
    borderRadius: 8,
    backgroundColor: '#4D3FD6',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  purpleBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: 'Inter_18pt-SemiBold',
  },
  outlineBtn: {
    marginTop: 8,
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#9A96C9',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  outlineBtnText: {
    color: '#4A4A67',
    fontSize: 16,
    fontFamily: 'Inter_18pt-SemiBold',
  },
  placeholderContainer: {
    flex: 1,
    backgroundColor: '#F8FBF3',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  placeholderTitle: {
    fontSize: 22,
    color: '#1A2620',
    fontFamily: 'Inter_18pt-Bold',
  },
  placeholderSub: {
    marginTop: 6,
    textAlign: 'center',
    color: '#516153',
    fontFamily: 'Inter_18pt-Regular',
  },
});

export const storeStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFF5E8',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 132,
  },
  patternIcon: {
    position: 'absolute',
    opacity: 0.34,
    zIndex: 0,
  },
  statusRow: {
    height: 31,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  timeText: {
    fontSize: 27,
    color: '#05070A',
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  statusRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  signalDots: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 3,
  },
  signalDot: {
    width: 4,
    borderRadius: 3,
    backgroundColor: '#05070A',
  },
  signalOne: {
    height: 8,
  },
  signalTwo: {
    height: 12,
  },
  signalThree: {
    height: 16,
  },
  signalFour: {
    height: 20,
  },
  wifiText: {
    marginTop: -3,
    color: '#05070A',
    fontSize: 26,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  battery: {
    width: 36,
    height: 18,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#05070A',
    padding: 2,
  },
  batteryFill: {
    flex: 1,
    borderRadius: 2,
    backgroundColor: '#05070A',
  },
  headerRow: {
    marginTop: 28,
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 70,
  },
  headerCopy: {
    flex: 1,
    marginLeft: 25,
  },
  title: {
    color: '#101214',
    fontSize: 35,
    lineHeight: 39,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  subtitle: {
    marginTop: 8,
    color: '#263444',
    fontSize: 18,
    lineHeight: 22,
    fontFamily: 'Inter_18pt-Medium',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 16,
  },
  circleAction: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#D8903D',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
  },
  cartBadge: {
    position: 'absolute',
    top: 4,
    right: 2,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#FF5A00',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  cartBadgeText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  promoRow: {
    marginTop: 32,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  promoCard: {
    flex: 1,
    minHeight: 122,
    borderRadius: 18,
    padding: 10,
    backgroundColor: '#FFFDF9',
    borderWidth: 1,
    borderColor: '#FFE0BD',
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#D38632',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
    elevation: 4,
  },
  promoCopy: {
    flex: 1,
    marginLeft: 4,
  },
  promoTitle: {
    fontSize: 16,
    lineHeight: 23,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  promoSub: {
    marginTop: 12,
    color: '#374151',
    fontSize: 13,
    fontFamily: 'Inter_18pt-Medium',
  },
  promoArrow: {
    width: 29,
    height: 29,
    borderRadius: 14.5,
    backgroundColor: '#FFE2BF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  arrowText: {
    marginTop: -3,
    color: '#FF5A00',
    fontSize: 28,
    fontFamily: 'Inter_18pt-Medium',
  },
  searchBox: {
    marginTop: 26,
    height: 74,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#FFE0BD',
    paddingHorizontal: 25,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#D88A31',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.07,
    shadowRadius: 15,
    elevation: 3,
  },
  searchPlaceholder: {
    marginLeft: 20,
    color: '#6B7280',
    fontSize: 20,
    fontFamily: 'Inter_18pt-Medium',
  },
  sectionHeader: {
    marginTop: 32,
    marginBottom: 16,
    paddingHorizontal: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: '#101214',
    fontSize: 22,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  viewAll: {
    color: '#FF5A00',
    fontSize: 18,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  frequentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  storeTile: {
    width: '18.4%',
    minHeight: 136,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#FFE2C2',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 18,
    paddingBottom: 16,
    shadowColor: '#D9903B',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 3,
  },
  logoWrap: {
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
  },
  frequentName: {
    color: '#121820',
    fontSize: 14,
    textAlign: 'center',
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  categoryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  categoryItem: {
    width: '19%',
    alignItems: 'center',
  },
  categoryIconCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 122, 20, 0.1)',
  },
  categoryText: {
    marginTop: 10,
    color: '#111827',
    fontSize: 12,
    textAlign: 'center',
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  sortRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  sortText: {
    color: '#FF5A00',
    fontSize: 20,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  sortChevron: {
    marginTop: -4,
    color: '#FF5A00',
    fontSize: 24,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  topStoreGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 16,
  },
  compactStoreTile: {
    width: '18.4%',
    minHeight: 150,
    paddingTop: 14,
    paddingBottom: 12,
  },
  compactLogoWrap: {
    height: 52,
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  offerText: {
    position: 'absolute',
    top: 14,
    color: '#FF5A00',
    fontSize: 12,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  topStoreName: {
    minHeight: 38,
    paddingHorizontal: 5,
    color: '#111827',
    fontSize: 12,
    lineHeight: 15,
    textAlign: 'center',
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  textLogo: {
    fontSize: 22,
    lineHeight: 26,
    textAlign: 'center',
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  singleLetterLogo: {
    fontSize: 46,
    lineHeight: 50,
  },
  mamaLogo: {
    fontSize: 17,
    lineHeight: 17,
  },
  bewakoofBadge: {
    backgroundColor: '#FFD800',
    borderRadius: 6,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  cashbackBanner: {
    marginTop: 25,
    minHeight: 122,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#FFE0BD',
    backgroundColor: '#FFF2E4',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#D9903B',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 3,
  },
  bannerCopy: {
    flex: 1,
    marginLeft: 12,
    marginRight: 10,
  },
  bannerTitle: {
    color: '#FF5A00',
    fontSize: 20,
    lineHeight: 25,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  bannerText: {
    marginTop: 9,
    color: '#243043',
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'Inter_18pt-Medium',
  },
  exploreButton: {
    width: 124,
    height: 54,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  exploreText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  exploreArrow: {
    color: '#FFFFFF',
    fontSize: 24,
    marginTop: -2,
    fontFamily: 'Inter_18pt-SemiBold',
  },
});

export const giftCardStyles = StyleSheet.create({
  /* ── Screen ── */
  screen: {
    flex: 1,
    backgroundColor: '#EEEAF8',
  },
  scrollContent: {
    paddingBottom: 120,
  },

  /* ── Background pattern layer ── */
  patternItem: {
    position: 'absolute',
    opacity: 0.18,
    zIndex: 0,
  },

  /* ── Status bar ── */
  statusRow: {
    height: 30,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  timeText: {
    fontSize: 14,
    color: '#1A1240',
    fontFamily: 'Inter_18pt-Bold',
  },
  statusRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  signalDots: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 2,
  },
  signalDot: {
    width: 3,
    borderRadius: 2,
    backgroundColor: '#1A1240',
  },
  signalOne: { height: 5 },
  signalTwo: { height: 8 },
  signalThree: { height: 11 },
  signalFour: { height: 14 },
  wifiText: {
    color: '#1A1240',
    fontSize: 14,
    fontFamily: 'Inter_18pt-Bold',
  },
  batteryOuter: {
    width: 20,
    height: 10,
    borderRadius: 2.5,
    borderWidth: 1.3,
    borderColor: '#1A1240',
    padding: 1.5,
  },
  batteryInner: {
    flex: 1,
    borderRadius: 1.5,
    backgroundColor: '#1A1240',
  },

  /* ── Header ── */
  headerRow: {
    paddingHorizontal: 16,
    paddingTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  backBtn: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 22,
    color: '#1A1240',
    fontFamily: 'Inter_18pt-ExtraBold',
  },

  /* ── Top 3 Nav Cards ── */
  topNavRow: {
    marginTop: 14,
    marginHorizontal: 14,
    flexDirection: 'row',
    gap: 8,
  },
  topNavCard: {
    flex: 1,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    paddingHorizontal: 10,
    alignItems: 'flex-start',
    shadowColor: '#5B3FD4',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  topNavCardActive: {
    backgroundColor: '#4A2FD8',
  },
  topNavIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#EEE9FC',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  topNavIconWrapActive: {
    backgroundColor: 'rgba(255,255,255,0.22)',
  },
  topNavLabel: {
    fontSize: 12,
    color: '#1A1240',
    fontFamily: 'Inter_18pt-Bold',
    marginTop: 2,
  },
  topNavLabelActive: {
    color: '#FFFFFF',
  },
  topNavSub: {
    fontSize: 9.5,
    color: '#7C6FAA',
    fontFamily: 'Inter_18pt-Regular',
    marginTop: 2,
  },
  topNavSubActive: {
    color: 'rgba(255,255,255,0.75)',
  },

  /* ── Cashback Banner ── */
  cashbackBanner: {
    marginTop: 14,
    marginHorizontal: 14,
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cashbackLeft: {
    flex: 1,
  },
  cashbackDivider: {
    width: 1,
    height: 44,
    backgroundColor: 'rgba(255,255,255,0.3)',
    marginHorizontal: 14,
  },
  cashbackRight: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cashbackLabel: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.78)',
    fontFamily: 'Inter_18pt-Medium',
    marginBottom: 3,
  },
  cashbackAmount: {
    fontSize: 24,
    color: '#FFFFFF',
    fontFamily: 'Inter_18pt-ExtraBold',
    letterSpacing: -0.5,
  },
  cashbackSub: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.7)',
    fontFamily: 'Inter_18pt-Regular',
    marginTop: 2,
  },
  cashbackArrow: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  /* ── Tab Row ── */
  tabRow: {
    marginTop: 14,
    paddingHorizontal: 14,
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#DDD8F0',
  },
  tabItem: {
    flex: 1,
    paddingBottom: 10,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 5,
  },
  tabItemActive: {
    borderBottomWidth: 2.5,
    borderBottomColor: '#4A2FD8',
  },
  tabLabel: {
    fontSize: 12,
    color: '#9591B0',
    fontFamily: 'Inter_18pt-Medium',
  },
  tabLabelActive: {
    color: '#4A2FD8',
    fontFamily: 'Inter_18pt-Bold',
  },

  /* ── Search Bar ── */
  searchBar: {
    marginTop: 14,
    marginHorizontal: 14,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    gap: 8,
    shadowColor: '#5B3FD4',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  searchPlaceholder: {
    flex: 1,
    fontSize: 13,
    color: '#A09CBB',
    fontFamily: 'Inter_18pt-Regular',
  },
  qrBtn: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },

  /* ── Section Header ── */
  sectionHeader: {
    marginTop: 18,
    marginHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 15,
    color: '#1A1240',
    fontFamily: 'Inter_18pt-Bold',
  },
  viewAllBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  viewAllText: {
    fontSize: 12,
    color: '#4A2FD8',
    fontFamily: 'Inter_18pt-SemiBold',
  },

  /* ── Category Brand Scroll ── */
  categoryScroll: {
    paddingHorizontal: 14,
  },
  categoryCard: {
    width: 80,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    paddingVertical: 10,
    paddingHorizontal: 6,
    alignItems: 'center',
    marginRight: 8,
    shadowColor: '#5B3FD4',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  categoryLogoWrap: {
    width: 56,
    height: 44,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
    overflow: 'hidden',
  },
  categoryBrandName: {
    fontSize: 11,
    color: '#1A1240',
    fontFamily: 'Inter_18pt-SemiBold',
    textAlign: 'center',
  },
  categoryOffer: {
    fontSize: 9.5,
    color: '#4A2FD8',
    fontFamily: 'Inter_18pt-Bold',
    marginTop: 2,
    textAlign: 'center',
  },

  /* ── Top Gift Cards Filters ── */
  filterScroll: {
    paddingHorizontal: 14,
  },
  filterItem: {
    alignItems: 'center',
    marginRight: 18,
    minWidth: 52,
  },
  filterIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#5B3FD4',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 6,
  },
  filterLabel: {
    fontSize: 10,
    color: '#4A4568',
    fontFamily: 'Inter_18pt-Medium',
    textAlign: 'center',
  },

  /* ── All Gift Cards List ── */
  allGiftCardsSection: {
    marginTop: 18,
    marginHorizontal: 14,
  },
  allGiftCardsTitle: {
    fontSize: 15,
    color: '#1A1240',
    fontFamily: 'Inter_18pt-Bold',
    marginBottom: 10,
  },
  giftCardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    marginBottom: 10,
    padding: 12,
    shadowColor: '#5B3FD4',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  giftCardThumb: {
    width: 72,
    height: 64,
    borderRadius: 10,
    overflow: 'hidden',
    marginRight: 12,
  },
  giftCardInfo: {
    flex: 1,
  },
  giftCardName: {
    fontSize: 15,
    color: '#1A1240',
    fontFamily: 'Inter_18pt-Bold',
    marginBottom: 3,
  },
  giftCardTypeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 3,
  },
  giftCardType: {
    fontSize: 11,
    color: '#7C6FAA',
    fontFamily: 'Inter_18pt-Medium',
  },
  giftCardTags: {
    fontSize: 10.5,
    color: '#9591B0',
    fontFamily: 'Inter_18pt-Regular',
    marginBottom: 4,
  },
  giftCardSave: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  giftCardSaveText: {
    fontSize: 12,
    color: '#2BC06A',
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  giftCardSaveChevron: {
    marginTop: 1,
  },
  giftCardMenu: {
    padding: 6,
    alignSelf: 'flex-start',
  },

  /* Brand logo backgrounds */
  thumbReliance: {
    backgroundColor: '#CC0000',
  },
  thumbPvr: {
    backgroundColor: '#111111',
  },
  thumbCleartrip: {
    backgroundColor: '#F05A28',
  },
  thumbLogoText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontFamily: 'Inter_18pt-Bold',
    textAlign: 'center',
  },
});

export const accountStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 15,
  },
  backBtn: {
    padding: 5,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: 'Inter_18pt-Bold',
    color: '#059669',
  },
  settingsBtn: {
    padding: 5,
  },
  profileSection: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  avatarContainer: {
    position: 'relative',
    marginBottom: 15,
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#E5E7EB',
  },
  userName: {
    fontSize: 20,
    fontFamily: 'Inter_18pt-Bold',
    color: '#111827',
  },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginTop: 5,
    gap: 4,
  },
  verifiedText: {
    fontSize: 12,
    color: '#16A34A',
    fontFamily: 'Inter_18pt-Medium',
  },
  userPhone: {
    fontSize: 14,
    color: '#4B5563',
    fontFamily: 'Inter_18pt-Regular',
    marginTop: 10,
  },
  userEmail: {
    fontSize: 14,
    color: '#4B5563',
    fontFamily: 'Inter_18pt-Regular',
    marginTop: 4,
  },
  editProfileBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#059669',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginTop: 20,
    gap: 8,
  },
  editProfileText: {
    fontSize: 14,
    color: '#059669',
    fontFamily: 'Inter_18pt-SemiBold',
  },
  section: {
    marginTop: 30,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontFamily: 'Inter_18pt-Bold',
    color: '#059669',
    marginBottom: 15,
  },
  earningsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  earningItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  earningIconBox: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#F0FDF4',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  earningInfo: {
    flex: 1,
  },
  earningLabel: {
    fontSize: 12,
    color: '#6B7280',
    fontFamily: 'Inter_18pt-Medium',
  },
  earningValue: {
    fontSize: 16,
    color: '#111827',
    fontFamily: 'Inter_18pt-Bold',
    marginTop: 2,
  },
  pendingValue: {
    color: '#F59E0B',
  },
  referralValue: {
    color: '#6366F1',
  },
  menuList: {
    marginTop: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#F9FAFB',
  },
  menuIconBox: {
    marginRight: 15,
  },
  menuTextContent: {
    flex: 1,
  },
  menuLabel: {
    fontSize: 15,
    color: '#111827',
    fontFamily: 'Inter_18pt-SemiBold',
  },
  menuSub: {
    fontSize: 12,
    color: '#6B7280',
    fontFamily: 'Inter_18pt-Regular',
    marginTop: 2,
  },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FECACA',
    borderRadius: 12,
    marginHorizontal: 20,
    marginTop: 40,
    paddingVertical: 14,
    gap: 8,
  },
  logoutText: {
    fontSize: 15,
    color: '#EF4444',
    fontFamily: 'Inter_18pt-Bold',
  },
});

export const kycStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    paddingBottom: 40,
    paddingHorizontal: 20,
  },
  statusCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FDF4',
    borderRadius: 16,
    padding: 20,
    marginTop: 20,
    gap: 15,
  },
  statusTextContent: {
    flex: 1,
  },
  statusTitle: {
    fontSize: 16,
    fontFamily: 'Inter_18pt-Bold',
    color: '#16A34A',
  },
  statusDesc: {
    fontSize: 12,
    color: '#16A34A',
    fontFamily: 'Inter_18pt-Medium',
    marginTop: 4,
    opacity: 0.8,
  },
  section: {
    marginTop: 30,
  },
  sectionTitle: {
    fontSize: 15,
    fontFamily: 'Inter_18pt-Bold',
    color: '#111827',
    marginBottom: 20,
  },
  field: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  fieldIconBox: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F0FDF4',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  fieldContent: {
    flex: 1,
  },
  fieldLabel: {
    fontSize: 11,
    color: '#6B7280',
    fontFamily: 'Inter_18pt-Medium',
  },
  fieldValue: {
    fontSize: 14,
    color: '#111827',
    fontFamily: 'Inter_18pt-SemiBold',
    marginTop: 2,
  },
  updateBanner: {
    marginTop: 30,
    backgroundColor: '#F0FDF4',
    borderRadius: 16,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  updateTextContent: {
    flex: 1,
  },
  updateTitle: {
    fontSize: 13,
    fontFamily: 'Inter_18pt-Bold',
    color: '#16A34A',
  },
  updateDesc: {
    fontSize: 11,
    color: '#16A34A',
    fontFamily: 'Inter_18pt-Medium',
    marginTop: 4,
    lineHeight: 16,
  },
  updateAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  updateBtnText: {
    fontSize: 12,
    color: '#16A34A',
    fontFamily: 'Inter_18pt-Bold',
  },
});

export const supportStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    paddingBottom: 40,
    paddingHorizontal: 20,
  },
  introTitle: {
    fontSize: 18,
    fontFamily: 'Inter_18pt-Bold',
    color: '#111827',
    marginTop: 20,
  },
  introSub: {
    fontSize: 14,
    color: '#6B7280',
    fontFamily: 'Inter_18pt-Regular',
    marginTop: 6,
  },
  supportGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 25,
    gap: 12,
  },
  supportCard: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  supportIconBox: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F0FDF4',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  supportLabel: {
    fontSize: 14,
    fontFamily: 'Inter_18pt-Bold',
    color: '#111827',
  },
  supportDesc: {
    fontSize: 11,
    color: '#6B7280',
    fontFamily: 'Inter_18pt-Regular',
    marginTop: 6,
    lineHeight: 16,
  },
  topicsSection: {
    marginTop: 35,
  },
  popularTitle: {
    fontSize: 15,
    fontFamily: 'Inter_18pt-Bold',
    color: '#111827',
    marginBottom: 15,
  },
  topicItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  topicText: {
    flex: 1,
    fontSize: 14,
    color: '#374151',
    fontFamily: 'Inter_18pt-Medium',
    marginLeft: 12,
  },
  viewAllFaqs: {
    marginTop: 25,
  },
  viewAllText: {
    fontSize: 14,
    color: '#059669',
    fontFamily: 'Inter_18pt-Bold',
  },
});

export const problemStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    paddingBottom: 40,
    paddingHorizontal: 20,
  },
  introTitle: {
    fontSize: 14,
    fontFamily: 'Inter_18pt-Bold',
    color: '#111827',
    marginTop: 20,
    marginBottom: 20,
  },
  issueCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    padding: 18,
    marginBottom: 12,
  },
  issueIconBox: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F0FDF4',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  issueContent: {
    flex: 1,
  },
  issueTitle: {
    fontSize: 14,
    fontFamily: 'Inter_18pt-Bold',
    color: '#111827',
  },
  issueSub: {
    fontSize: 11,
    color: '#6B7280',
    fontFamily: 'Inter_18pt-Regular',
    marginTop: 4,
  },
  helpBanner: {
    marginTop: 30,
    backgroundColor: '#F0FDF4',
    borderRadius: 16,
    padding: 20,
  },
  helpHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  helpTitle: {
    fontSize: 14,
    fontFamily: 'Inter_18pt-Bold',
    color: '#065F46',
  },
  helpDesc: {
    fontSize: 12,
    color: '#065F46',
    fontFamily: 'Inter_18pt-Medium',
    lineHeight: 18,
    marginBottom: 20,
  },
  contactBtn: {
    backgroundColor: '#166534',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
  },
  contactBtnText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontFamily: 'Inter_18pt-Bold',
  },
});

export const settingsStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    paddingBottom: 40,
    paddingHorizontal: 20,
  },
  section: {
    marginTop: 25,
  },
  sectionTitle: {
    fontSize: 14,
    fontFamily: 'Inter_18pt-Bold',
    color: '#059669',
    marginBottom: 15,
  },
  settingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: 15,
    gap: 15,
  },
  settingIconBox: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#F9FAFB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingContent: {
    flex: 1,
  },
  settingLabel: {
    fontSize: 14,
    color: '#111827',
    fontFamily: 'Inter_18pt-SemiBold',
  },
  settingSub: {
    fontSize: 11,
    color: '#6B7280',
    fontFamily: 'Inter_18pt-Regular',
    marginTop: 2,
  },
  logoutItem: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
    paddingVertical: 15,
  },
  logoutLabel: {
    fontSize: 14,
    color: '#EF4444',
    fontFamily: 'Inter_18pt-Bold',
  },
  logoutSub: {
    fontSize: 11,
    color: '#EF4444',
    fontFamily: 'Inter_18pt-Regular',
    marginTop: 2,
    opacity: 0.8,
  },
});

export const tabNavigationStyles = StyleSheet.create({
  tabBar: {
    height: 96,
    marginHorizontal: 14,
    marginBottom: 14,
    borderRadius: 18,
    paddingTop: 8,
    paddingBottom: 10,
    borderTopWidth: 0,
    borderWidth: 1,
    borderColor: '#FFE0BD',
    backgroundColor: '#FFFFFF',
    position: 'absolute',
    shadowColor: '#D9903B',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 8,
  },
  iconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  iconWrapFocused: {
    backgroundColor: 'transparent',
  },
  tabLabel: {
    fontSize: 12,
    fontFamily: 'Inter_18pt-Medium',
  },
  tabLabelActive: {
    color: '#FF5A00',
    fontFamily: 'Inter_18pt-Bold',
  },
  tabLabelInactive: {
    color: '#374151',
  },
});

export const cashbackStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFFFFF' },
  scrollContent: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 132 },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 10,
  },
  headerCopy: { flex: 1, marginLeft: 12 },
  title: { fontSize: 24, fontFamily: 'Inter_18pt-ExtraBold', color: '#111827' },
  subtitle: {
    fontSize: 13,
    color: '#6B7280',
    fontFamily: 'Inter_18pt-Medium',
    marginTop: 2,
  },
  headerActions: { flexDirection: 'row', gap: 12 },
  actionBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  badge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#16A34A',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  badgeText: { color: '#FFFFFF', fontSize: 11, fontFamily: 'Inter_18pt-Bold' },

  promoRow: { flexDirection: 'row', gap: 10, marginBottom: 20 },
  promoCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'flex-start',
  },
  promoIcon: { width: 40, height: 40, marginBottom: 8 },
  promoLabel: { fontSize: 14, fontFamily: 'Inter_18pt-Bold', color: '#111827' },
  promoValue: {
    fontSize: 11,
    color: '#16A34A',
    fontFamily: 'Inter_18pt-Bold',
    marginTop: 4,
  },

  searchBox: {
    height: 54,
    borderRadius: 12,
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 20,
  },
  searchPlaceholder: {
    marginLeft: 10,
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: 'Inter_18pt-Regular',
  },

  generatorCard: {
    backgroundColor: '#F0FDF4',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#DCFCE7',
    marginBottom: 24,
  },
  generatorTitle: {
    fontSize: 16,
    fontFamily: 'Inter_18pt-Bold',
    color: '#166534',
    marginBottom: 16,
  },
  inputRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  linkInputWrap: {
    flex: 1,
    height: 50,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D1FAE5',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  linkInput: { flex: 1, marginLeft: 8, fontSize: 13, color: '#111827' },
  generateBtn: {
    height: 50,
    backgroundColor: '#16A34A',
    borderRadius: 10,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  generateBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'Inter_18pt-Bold',
  },

  howItWorks: { marginTop: 8 },
  howTitle: {
    fontSize: 14,
    fontFamily: 'Inter_18pt-Bold',
    color: '#166534',
    marginBottom: 16,
  },
  stepsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stepItem: { alignItems: 'center', width: '22%' },
  stepCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#16A34A',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  stepText: {
    fontSize: 11,
    fontFamily: 'Inter_18pt-Bold',
    color: '#111827',
    textAlign: 'center',
  },
  stepSub: {
    fontSize: 9,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 4,
    lineHeight: 12,
  },
  stepArrow: { fontSize: 20, color: '#D1FAE5' },

  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: 'Inter_18pt-Bold',
    color: '#111827',
  },
  viewAll: { fontSize: 14, color: '#16A34A', fontFamily: 'Inter_18pt-Bold' },

  storesRow: { flexDirection: 'row', gap: 12, marginBottom: 24 },
  storeTile: { width: 75, alignItems: 'center' },
  storeLogoBox: {
    width: 75,
    height: 75,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  storeName: {
    fontSize: 11,
    fontFamily: 'Inter_18pt-Bold',
    color: '#111827',
    textAlign: 'center',
  },

  categoryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  categoryItem: { alignItems: 'center', width: '18%' },
  catIconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  catName: {
    fontSize: 11,
    fontFamily: 'Inter_18pt-Bold',
    color: '#111827',
    textAlign: 'center',
  },

  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  compactTile: { width: '18.4%', alignItems: 'center', marginBottom: 16 },
  compactLogoBox: {
    width: '100%',
    height: 75,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  offerText: {
    fontSize: 10,
    color: '#16A34A',
    fontFamily: 'Inter_18pt-Bold',
    marginBottom: 4,
  },
  compactName: {
    fontSize: 10,
    fontFamily: 'Inter_18pt-Bold',
    color: '#111827',
    textAlign: 'center',
  },

  bottomBanner: {
    backgroundColor: '#F0FDF4',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
  },
  bannerCopy: { flex: 1, marginRight: 12 },
  bannerTitle: {
    fontSize: 16,
    fontFamily: 'Inter_18pt-Bold',
    color: '#166534',
  },
  bannerDesc: { fontSize: 12, color: '#166534', marginTop: 4, opacity: 0.8 },
  exploreBtn: {
    backgroundColor: '#16A34A',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  exploreText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'Inter_18pt-Bold',
  },
});
