import { StyleSheet } from 'react-native';

export const loginStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F8FBF3' },
  screen: {
    flex: 1,
    backgroundColor: '#F8FBF3',
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 28,
  },
  absCash: {
    position: 'absolute',
    zIndex: 1,
  },
  absDecor: {
    position: 'absolute',
    opacity: 0.55,
    zIndex: 0,
  },
  brandWrap: {
    alignItems: 'center',
    marginTop: 14,
  },
  brandMain: {
    fontSize: 46,
    fontFamily: 'Inter_18pt-ExtraBold',
    color: '#111410',
    letterSpacing: -1.2,
    zIndex: 2,
  },
  brandAccent: {
    color: '#5F983A',
  },
  brandSub: {
    marginTop: 4,
    fontSize: 13,
    fontFamily: 'Inter_18pt-Medium',
    color: '#61695D',
    letterSpacing: 1.4,
  },
  heroPad: {
    height: 275,
  },
  featuresCard: {
    marginTop: 10,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DFE9D5',
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-around',
    elevation: 2,
    shadowColor: '#5E8F3A',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  featureCol: {
    width: '32%',
    alignItems: 'center',
    position: 'relative',
  },
  featureIconCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#EEF5E7',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  featureTitle: {
    fontSize: 12,
    fontFamily: 'Inter_18pt-Bold',
    color: '#182017',
  },
  featureSub: {
    marginTop: 1,
    fontSize: 10,
    fontFamily: 'Inter_18pt-Regular',
    color: '#5A6355',
    textAlign: 'center',
  },
  featureDivider: {
    position: 'absolute',
    right: -6,
    top: 6,
    width: 1,
    height: 42,
    backgroundColor: '#E2EBDD',
  },
  welcomeTitle: {
    marginTop: 20,
    fontSize: 34,
    fontFamily: 'Inter_18pt-Bold',
    color: '#172015',
  },
  welcomeSub: {
    marginTop: 4,
    marginBottom: 14,
    fontSize: 13,
    fontFamily: 'Inter_18pt-Regular',
    color: '#6B7467',
  },
  phoneInput: {
    minHeight: 52,
    borderRadius: 14,
    borderWidth: 1.4,
    borderColor: '#AFC49A',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  countryCode: {
    fontSize: 29,
    fontFamily: 'Inter_18pt-SemiBold',
    color: '#469739',
  },
  dropdown: {
    marginLeft: 6,
    marginRight: 10,
    fontSize: 16,
    color: '#6F7A68',
  },
  verticalDivider: {
    height: 24,
    width: 1,
    backgroundColor: '#CBD8BE',
    marginRight: 12,
  },
  phoneTextInput: {
    flex: 1,
    fontSize: 17,
    color: '#232A1F',
    fontFamily: 'Inter_18pt-Regular',
    paddingVertical: 8,
  },
  continueBtn: {
    marginTop: 12,
    minHeight: 48,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  continueText: {
    color: '#101610',
    fontSize: 19,
    fontFamily: 'Inter_18pt-SemiBold',
  },
  continueArrow: {
    color: '#101610',
    fontSize: 20,
    marginTop: -2,
    fontFamily: 'Inter_18pt-SemiBold',
  },
  cashbackCard: {
    marginTop: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#DFE9D5',
    backgroundColor: '#FFFFFF',
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
    flexDirection: 'row',
  },
  cashbackTextWrap: {
    flex: 1,
    marginLeft: 8,
  },
  cashbackTop: {
    fontSize: 14,
    color: '#4C5844',
    fontFamily: 'Inter_18pt-Regular',
  },
  cashbackMid: {
    marginTop: 1,
    fontSize: 27,
    lineHeight: 31,
    color: '#4B9139',
    fontFamily: 'Inter_18pt-Bold',
  },
  cashbackBottom: {
    marginTop: 2,
    fontSize: 18,
    color: '#7F8A77',
    fontFamily: 'Inter_18pt-Regular',
  },
  trustedRow: {
    marginTop: 14,
    marginBottom: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  trustedText: {
    color: '#5E6858',
    fontSize: 13,
    fontFamily: 'Inter_18pt-Regular',
  },
  trustedBold: {
    color: '#2D7E2A',
    fontFamily: 'Inter_18pt-Bold',
  },
});

export const otpStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F8FBF3' },
  screen: {
    flex: 1,
    backgroundColor: '#F8FBF3',
  },
  content: {
    paddingHorizontal: 18,
    paddingBottom: 28,
  },
  absCash: {
    position: 'absolute',
    zIndex: 0,
  },
  absDecor: {
    position: 'absolute',
    opacity: 0.45,
    zIndex: 0,
  },
  backArrow: {
    marginTop: 8,
    fontSize: 30,
    color: '#101410',
    width: 28,
    fontFamily: 'Inter_18pt-Regular',
  },
  brandWrap: {
    alignItems: 'center',
    marginTop: 12,
  },
  brandMain: {
    fontSize: 62,
    color: '#111410',
    letterSpacing: -1.3,
    fontFamily: 'Inter_18pt-ExtraBold',
  },
  brandAccent: {
    color: '#5F983A',
  },
  brandSub: {
    marginTop: 2,
    fontSize: 12,
    letterSpacing: 1.3,
    color: '#465141',
    fontFamily: 'Inter_18pt-Medium',
  },
  lockWrap: {
    marginTop: 28,
    marginBottom: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 50,
    color: '#1B3528',
    textAlign: 'center',
    fontFamily: 'Inter_18pt-Bold',
  },
  subtitle: {
    marginTop: 4,
    fontSize: 12,
    color: '#667067',
    textAlign: 'center',
    fontFamily: 'Inter_18pt-Regular',
  },
  phoneRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  phoneNumber: {
    fontSize: 19,
    color: '#182018',
    textAlign: 'center',
    fontFamily: 'Inter_18pt-Bold',
  },
  editIcon: {
    color: '#5A9B39',
    fontSize: 14,
  },
  otpPrompt: {
    marginTop: 20,
    marginBottom: 8,
    fontSize: 14,
    textAlign: 'center',
    color: '#454E45',
    fontFamily: 'Inter_18pt-Medium',
  },
  otpRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    paddingHorizontal: 6,
  },
  otpBox: {
    width: 53,
    height: 61,
    borderRadius: 10,
    borderWidth: 1.4,
    borderColor: '#91B576',
    backgroundColor: '#F8FBF3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  otpBoxActive: {
    borderColor: '#6A9F46',
    backgroundColor: '#FBFEF9',
  },
  cursorLine: {
    width: 2.5,
    height: 26,
    borderRadius: 2,
    backgroundColor: '#5E9A3E',
  },
  expireText: {
    textAlign: 'center',
    color: '#586257',
    fontSize: 15,
    fontFamily: 'Inter_18pt-Regular',
  },
  timerText: {
    color: '#63A33F',
    fontFamily: 'Inter_18pt-Bold',
  },
  resendText: {
    marginTop: 8,
    textAlign: 'center',
    color: '#596358',
    fontSize: 14,
    fontFamily: 'Inter_18pt-Regular',
  },
  resendLink: {
    color: '#5E9E3C',
    fontFamily: 'Inter_18pt-Bold',
  },
  securityCard: {
    marginTop: 18,
    borderRadius: 12,
    backgroundColor: '#EEF4E8',
    borderWidth: 1,
    borderColor: '#E3EED8',
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  securityIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    backgroundColor: '#E8F1DE',
  },
  securityTextWrap: {
    flex: 1,
  },
  securityTitle: {
    fontSize: 12,
    color: '#283229',
    fontFamily: 'Inter_18pt-SemiBold',
  },
  securitySub: {
    marginTop: 1,
    fontSize: 10,
    color: '#5A635B',
    fontFamily: 'Inter_18pt-Regular',
  },
  verifyBtn: {
    marginTop: 18,
    minHeight: 56,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  verifyText: {
    color: '#111610',
    fontSize: 17,
    fontFamily: 'Inter_18pt-SemiBold',
  },
  verifyArrow: {
    color: '#111610',
    fontSize: 23,
    marginTop: -2,
    fontFamily: 'Inter_18pt-SemiBold',
  },
  trustedRow: {
    marginTop: 14,
    marginBottom: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  laurel: {
    color: '#6EA14A',
    fontSize: 16,
    marginTop: -1,
  },
  trustedText: {
    color: '#4F5A4D',
    fontSize: 13,
    fontFamily: 'Inter_18pt-Regular',
  },
  trustedBold: {
    color: '#3E8A2E',
    fontFamily: 'Inter_18pt-Bold',
  },
});

export const homeStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F8FBF3' },
  container: { flex: 1, backgroundColor: '#F8FBF3' },
  scrollContent: { paddingHorizontal: 12, paddingTop: 8, paddingBottom: 16 },
  hero: {
    borderRadius: 18,
    backgroundColor: '#F2F8EC',
    borderWidth: 1,
    borderColor: '#E4EFDA',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  heroRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  heroLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  heroIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#16A34A',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  heroTitle: { fontSize: 20, color: '#1A2020', fontFamily: 'Inter_18pt-Bold' },
  heroSub: { fontSize: 11, color: '#374437', marginTop: 2, fontFamily: 'Inter_18pt-Regular' },
  heroWalletWrap: { alignItems: 'center', justifyContent: 'center' },
  coinsRow: { position: 'absolute', bottom: -4, left: -6, right: -6, flexDirection: 'row', justifyContent: 'space-between' },
  coinBubble: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#F5C94C',
    alignItems: 'center',
    justifyContent: 'center',
  },
  offerList: { marginTop: 10 },
  offerCard: {
    width: 92,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E3EAE0',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 8,
    paddingVertical: 10,
    marginRight: 8,
  },
  offerLogoWrap: {
    height: 30,
    justifyContent: 'center',
  },
  offerBrand: { fontSize: 11, color: '#121212', fontFamily: 'Inter_18pt-SemiBold', minHeight: 34 },
  offerUpto: { fontSize: 10, color: '#586258', marginTop: 6, fontFamily: 'Inter_18pt-Regular' },
  offerPercent: { fontSize: 36, color: '#18803C', fontFamily: 'Inter_18pt-Bold' },
  offerCashback: { fontSize: 11, color: '#586258', fontFamily: 'Inter_18pt-Regular' },
  offerTag: { marginTop: 8, fontSize: 10, color: '#18803C', fontFamily: 'Inter_18pt-Bold' },
  ctaButton: {
    marginTop: 8,
    minHeight: 42,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  ctaText: { fontSize: 16, color: '#FFFFFF', fontFamily: 'Inter_18pt-SemiBold' },
  sectionCard: {
    marginTop: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2EADF',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  featureRow: { flexDirection: 'row' },
  featureItem: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRightWidth: 1,
    borderRightColor: '#E9EFE4',
  },
  featureItemLast: { borderRightWidth: 0 },
  featureHead: { fontSize: 14, color: '#2C8A37', fontFamily: 'Inter_18pt-Bold' },
  featureSub: { fontSize: 11, color: '#4E5A4E', marginTop: 2, fontFamily: 'Inter_18pt-Regular' },
  allStoreCard: {
    marginTop: 10,
    borderRadius: 14,
    backgroundColor: '#FFF2E7',
    borderWidth: 1,
    borderColor: '#F3DFCD',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  allStoreTitle: { fontSize: 19, color: '#C56911', fontFamily: 'Inter_18pt-Bold' },
  allStoreSub: { fontSize: 12, color: '#2D3632', marginTop: 3, fontFamily: 'Inter_18pt-Regular' },
  secondaryBtn: {
    marginTop: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#F1D0AF',
    paddingHorizontal: 13,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  secondaryBtnText: { fontSize: 14, color: '#B55C08', fontFamily: 'Inter_18pt-SemiBold' },
  giftCardWrap: {
    marginTop: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E6E4F6',
    backgroundColor: '#F5F4FD',
    padding: 10,
  },
  giftTitleRow: { flexDirection: 'row', alignItems: 'center' },
  giftTitle: { fontSize: 34, color: '#23233A', fontFamily: 'Inter_18pt-Bold', marginLeft: 8 },
  giftSub: { fontSize: 11, color: '#3D3D56', marginTop: 2, marginLeft: 38, fontFamily: 'Inter_18pt-Regular' },
  giftList: { marginTop: 10, flexDirection: 'row', justifyContent: 'space-between' },
  giftItem: {
    width: '19%',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E7E8EF',
    paddingBottom: 6,
    overflow: 'hidden',
  },
  giftLogoWrap: {
    height: 44,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#EFF1F4',
  },
  giftLogo: { height: 44, backgroundColor: '#111214', alignItems: 'center', justifyContent: 'center' },
  giftLogoBlue: { backgroundColor: '#0A54B4' },
  giftLogoPink: { backgroundColor: '#D63384' },
  giftLogoGreen: { backgroundColor: '#18803C' },
  giftLogoText: { color: '#FFFFFF', fontSize: 11, fontFamily: 'Inter_18pt-Bold' },
  giftItemName: { fontSize: 9, color: '#1D2420', paddingHorizontal: 4, paddingTop: 5, fontFamily: 'Inter_18pt-SemiBold' },
  giftItemPct: { fontSize: 9, color: '#4A57C6', paddingHorizontal: 4, marginTop: 1, fontFamily: 'Inter_18pt-Bold' },
  purpleBtn: {
    marginTop: 10,
    minHeight: 34,
    borderRadius: 8,
    backgroundColor: '#4D3FD6',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  purpleBtnText: { color: '#FFFFFF', fontSize: 16, fontFamily: 'Inter_18pt-SemiBold' },
  outlineBtn: {
    marginTop: 8,
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#9A96C9',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  outlineBtnText: { color: '#4A4A67', fontSize: 16, fontFamily: 'Inter_18pt-SemiBold' },
  placeholderContainer: { flex: 1, backgroundColor: '#F8FBF3', alignItems: 'center', justifyContent: 'center', padding: 24 },
  placeholderTitle: { fontSize: 22, color: '#1A2620', fontFamily: 'Inter_18pt-Bold' },
  placeholderSub: { marginTop: 6, textAlign: 'center', color: '#516153', fontFamily: 'Inter_18pt-Regular' },
});

export const tabNavigationStyles = StyleSheet.create({
  tabBar: {
    height: 66,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingTop: 8,
    paddingBottom: 6,
    borderTopWidth: 1,
    borderColor: '#E3EBDE',
    backgroundColor: '#FFFFFF',
  },
  iconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  iconWrapFocused: {
    backgroundColor: '#2FA346',
  },
  tabLabel: {
    fontSize: 10,
    fontFamily: 'Inter_18pt-Medium',
  },
  tabLabelActive: {
    color: '#1F9E43',
  },
  tabLabelInactive: {
    color: '#6B7280',
  },
});
